export enum NotificationEvent {
  // Payment
  PAYMENT_SUCCESS = 'PAYMENT_SUCCESS',

  // Problem report
  NEW_PROBLEM_REPORT = 'NEW_PROBLEM_REPORT',

  // Submission
  PROBLEM_SOLVED = 'PROBLEM_SOLVED',

  // Discuss
  POST_PUBLISHED = 'POST_PUBLISHED',
  POST_COMMENT = 'POST_COMMENT',
  POST_COMMENT_REPLY = 'POST_COMMENT_REPLY',

  // Solution
  SOLUTION_COMMENT = 'SOLUTION_COMMENT',
  SOLUTION_COMMENT_REPLY = 'SOLUTION_COMMENT_REPLY',

  // Problem comment
  PROBLEM_COMMENT_REPLY = 'PROBLEM_COMMENT_REPLY',

  // Study plan
  STUDY_PLAN_COMPLETED = 'STUDY_PLAN_COMPLETED',
  STUDY_PLAN_MILESTONE = 'STUDY_PLAN_MILESTONE',
  STUDY_PLAN_DAY_COMPLETED = 'STUDY_PLAN_DAY_COMPLETED',
}
