export enum NotificationType {
  SYSTEM = 'SYSTEM',
  COMMENT = 'COMMENT',
  REPLY = 'REPLY',
  CONTEST = 'CONTEST',
  MENTION = 'MENTION',
  STUDY_PLAN = 'STUDY_PLAN',
  PAYMENT = 'PAYMENT',
  SUBMISSION = 'SUBMISSION',
  DISCUSS = 'DISCUSS',
}
