name: CI

on:
  pull_request:
    branches: ['**']
    paths:
      - 'src/**'
      - 'test/**'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig*.json'
      - 'nest-cli.json'
      - 'eslint.config.mjs'
      - '.prettierrc'
      - 'Dockerfile'
      - '.github/workflows/ci.yml'
  push:
    branches: ['**']
    paths:
      - 'src/**'
      - 'test/**'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig*.json'
      - 'nest-cli.json'
      - 'eslint.config.mjs'
      - '.prettierrc'
      - 'Dockerfile'
      - '.github/workflows/ci.yml'

jobs:
  lint:
    uses: TQTuyen/ci-cd-toolkit/.github/workflows/ci-lint.yml@main
    with:
      package-manager: npm
      node-version: 24

  build:
    uses: TQTuyen/ci-cd-toolkit/.github/workflows/ci-build.yml@main
    with:
      package-manager: npm
      node-version: 24

  push-image:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: [lint, build]
    permissions:
      contents: read
      id-token: write
    uses: TQTuyen/ci-cd-toolkit/.github/workflows/cd-deploy-gar.yml@main
    with:
      repository: ${{ vars.GCP_PROJECT_ID }}/sfinx/sfinx-backend
      gcp-region: asia-southeast1
    secrets:
      wif-provider: ${{ secrets.GCP_WIF_PROVIDER }}
      service-account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
